trigger:
- main

resources:
  repositories:
    - repository: apprepo
      type: github
      name: batooalqudah/nodeJs-app-for-testing
      ref: main

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    pool: 
      vmImage: ubuntu-latest
    steps:
    - checkout: apprepo
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: batooalqudah/myapp
        dockerfile: Dockerfile
        containerRegistry: docker-hub
        tags: |
          $(Build.BuildId)

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployGreen
    pool: 
      name: green-pool
    steps:
    - script: |
        docker pull batooalqudah/myapp:$(Build.BuildId)
        docker stop myapp || true
        docker rm myapp || true
        docker run -d --name myapp -p 80:3000 batooalqudah/myapp:$(Build.BuildId)
