
trigger:
- main

stages:

- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build & Push to DockerHub
    pool: 
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        repository: batooalqudah/myapp
        dockerfile: Dockerfile
        containerRegistry: docker-hub
        tags: |
          $(Build.BuildId)

- stage: Deploy
  displayName: Deploy to Green Server
  dependsOn: Build
  jobs:
  - job: DeployGreen
    displayName: Deploy to Green Server
    pool: 
      name: green-pool
    steps:
    - script: |
        docker pull batooalqudah/myapp:$(Build.BuildId)
        docker stop myapp || true
        docker rm myapp || true
        docker run -d --name myapp -p 80:3000 batooalqudah/myapp:$(Build.BuildId)
